services:
  web-data-viz:
    image: raniersptech/infrawatch:site_1.2
    env_file:
      - ../../web-data-viz/.env
    ports:
      - "8080:8000"
    networks:
      - infranet
    depends_on:
      - db

  db:
    image: raniersptech/infrawatch:db_1.2
    ports:
      - "3306:3306"
    networks:
      - infranet

networks:
  infranet:
    driver: bridge