services:
  web-data-viz:
    image: raniersptech/infrawatch:site_1.0t
    ports:
      - "8080:8000"
    networks:
      - infranet
    depends_on:
      - db

  db:
    image: raniersptech/infrawatch:db_1.1
    ports:
      - "3306:3306"
    networks:
      - infranet

networks:
  infranet:
    driver: bridge